version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mcesar
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbUser
      ME_CONFIG_MONGODB_URL: mongodb://mcesar:dbUser@mymoney:27017/